name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    environment: first

    steps:
      - uses: actions/checkout@v3

      - name: Show environment
        run: set

  second:
    runs-on: ubuntu-latest
    environment: second
    needs: first

    steps:
      - uses: actions/checkout@v3

      - name: Show environment
        run: set

  third:
    runs-on: ubuntu-latest
    environment: third
    needs: second

    steps:
      - uses: actions/checkout@v3

      - name: Show environment
        run: set
