name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show environment
        run: set

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: test-ci-dispatch
          repository: dex4er/test-ci
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
