name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    environment: testing

    steps:
      - uses: actions/checkout@v3

      - name: Show environment
        run: set

      - name: Repository Dispatch
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: dex4er
          repo: dex4er/test-ci
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: ci.yml
          client_payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: testing

    steps:
      - uses: actions/checkout@v3

      - name: Show environment
        run: set

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: test-ci-dispatch
          repository: dex4er/test-ci
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: staging

    steps:
      - uses: actions/checkout@v3

      - name: Show environment
        run: set

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: test-ci-dispatch
          repository: dex4er/test-ci
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
